# Generated by Django 4.1.1 on 2022-09-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueitem",
            name="encrypt_before_sending",
            field=models.BooleanField(default=True, verbose_name="encrypt"),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
