# Generated by Django 4.1.1 on 2022-10-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0002_alter_queueitem_encrypt_before_sending_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queueitem",
            name="retries_allowed",
        ),
        migrations.RemoveField(
            model_name="source",
            name="default_retry_count_allowed",
        ),
    ]
